"""Generated gRPC stubs for AgilePlus.

Implements FR-053 to FR-057. See WP00.

Stubs are generated by `buf generate` into `src/gen/`.
Re-export generated modules here for downstream consumption.
"""

# Generated stubs will be available after running `buf generate`.
# Import paths depend on buf codegen output structure.
# Example (after generation):
#   from agileplus_proto.gen.agileplus.v1 import common_pb2
#   from agileplus_proto.gen.agileplus.v1 import core_pb2
#   from agileplus_proto.gen.agileplus.v1 import core_pb2_grpc
#   from agileplus_proto.gen.agileplus.v1 import agents_pb2
#   from agileplus_proto.gen.agileplus.v1 import agents_pb2_grpc
#   from agileplus_proto.gen.agileplus.v1 import integrations_pb2
#   from agileplus_proto.gen.agileplus.v1 import integrations_pb2_grpc
