[package]
name = "phenotype-test-infra"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
description = "TODO"

[lib]
path = "src/lib.rs"

[dependencies]
phenotype-error-core.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-test.workspace = true
uuid.workspace = true
