[package]
name = "phenotype-state-machine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Phenotype shared crate"

[dependencies]
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
parking_lot.workspace = true
