[package]
name = "phenotype-errors"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Error types for phenotype crates"

[dependencies]
phenotype-error-core = { path = "../phenotype-error-core" }
serde = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
regex.workspace = true
tokio = { workspace = true, features = ["full"], optional = true }

[dev-dependencies]

[features]
default = []
serde-support = ["serde", "phenotype-error-core/serde"]
tokio-support = ["tokio"]
