[package]
name = "phenotype-telemetry"
version = "0.2.0"
edition = "2021"
authors = ["Phenotype Team"]
license = "MIT"
description = "Phenotype Telemetry"

[lib]
path = "src/lib.rs"

[dependencies]
phenotype-error-core = { version = "0.1.0", path = "../phenotype-error-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "fmt"] }
dashmap = "5"
tokio = { version = "1", features = ["full"] }
