name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-env
        with:
          rust-version: stable

      - uses: ./.github/actions/run-tests
        with:
          test-command: cargo test --all
          lint-command: cargo clippy -- -D warnings
